USE [master]
GO

/****** Object:  Database [ServiceDB]    Script Date: 10/07/2018 03:13:27 ******/
CREATE DATABASE [ServiceDB] ON  PRIMARY 
( NAME = N'ServiceDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\ServiceDB.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'ServiceDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\ServiceDB_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [ServiceDB] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ServiceDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ServiceDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ServiceDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ServiceDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ServiceDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ServiceDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [ServiceDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ServiceDB] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [ServiceDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ServiceDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ServiceDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ServiceDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ServiceDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ServiceDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ServiceDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ServiceDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ServiceDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ServiceDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ServiceDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ServiceDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ServiceDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ServiceDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ServiceDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ServiceDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ServiceDB] SET  READ_WRITE 
GO

ALTER DATABASE [ServiceDB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [ServiceDB] SET  MULTI_USER 
GO

ALTER DATABASE [ServiceDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ServiceDB] SET DB_CHAINING OFF 
GO


